spring:
  application:
    name: e-commerce-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce_db
    username: e_commerce
    password: e_commerce

file:
  upload-dir: /home/dang-quang/Documents/Projects/E-commerce/images/