spring:
  application:
    name: e-commerce-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce
    username: postgres
    password: 123

file:
  upload-dir: C:\Users\trinh\OneDrive\Documents\Projects\E-commerce\images\